name: Go

on:
  push:
    branches: [action]
  pull_request:
    branches: [action]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Echo Ubuntu version
        run: |
          cat /etc/os-release

      - name: Build for python 3.8
        run: |
          sudo apt-get install -y python3-numpy
          go build -v .

      - name: Build for python 3.7
        run: |
          sudo apt-get install -y python3.7 python3.7-dev
          # python3.7 -m pip install numpy
          # PYTHONVER=$(python3 --version | grep -Po "(?<=Python )3.[0-9]+")
          # export CGO_CFLAGS="-I${HOME}/.local/lib/python${PYTHONVER}/site-packages/numpy/core/include"
          go build -tags=py37 -v .
      - name: Build for python 3.6
        run: |
          sudo apt-get install -y python3.6 python3.6-dev
          go build --tags=py36 -v .
      # - name: Test
      #   run: |
      #     python3 -m pip install numpy
      #     PYTHONVER=$(python3 --version | grep -Po "(?<=Python )3.[0-9]+")
      #     export CGO_CFLAGS="-I${HOME}/.local/lib/python${PYTHONVER}/site-packages/numpy/core/include"
      #     go test -v .
