name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  py38:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          sudo apt-get install -y python3 python3-dev python3-numpy
          go build -v .

      - name: Test
        run: |
          sudo apt-get install -y python3 python3-dev python3-numpy
          for i in {1..10}; do go test -v .; done

  py36:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          sudo apt-get install -y python3 python3-dev python3-numpy
          go build --tags=py36 -v .

      - name: Test
        run: |
          sudo apt-get install -y python3 python3-dev python3-numpy
          for i in {1..10}; do go test --tags=py36 -v .; done
