name: Go

on:
  push:
    branches: [action]
  pull_request:
    branches: [action]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          pwd
          which python3
          python3 --version
          ls -l /usr/include
          ls -l /usr/include/python3.8
          ls -l /usr/lib
          ls -l /usr/lib/python3.8
          ls -l /usr/lib/python3.8/site-packages
          ls -l /usr/lib/x86_64-linux-gnu
          ls -l /usr/local/lib/python3.8/dist-packages
          python3 -m pip install numpy
          PYTHONVER=$(python3 --version | grep -Po "(?<=Python )3.[0-9]+")
          export CGO_CFLAGS="-I${HOME}/.local/lib/python${PYTHONVER}/site-packages/numpy/core/include"
          go build -v .

      - name: Test
        run: |
          python3 -m pip install numpy
          PYTHONVER=$(python3 --version | grep -Po "(?<=Python )3.[0-9]+")
          export CGO_CFLAGS="-I${HOME}/.local/lib/python${PYTHONVER}/site-packages/numpy/core/include"
          go test -v .
