name: Go

on:
  push:
    branches: [action]
  pull_request:
    branches: [action]

jobs:
  py38:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Echo Ubuntu version
        run: |
          cat /etc/os-release

      - name: Build
        run: |
          sudo apt-get install -y python3 python3-dev python3-numpy
          go build -v .

      - name: Test
        run: |
          sudo apt-get install -y python3 python3-dev python3-numpy
          go test -v .

  py36:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Echo Ubuntu version
        run: |
          cat /etc/os-release

      - name: Build
        run: |
          sudo apt-get install -y python3 python3-dev python3-numpy
          go build --tags=py36 -v .

      - name: Test
        run: |
          sudo apt-get install -y python3 python3-dev python3-numpy
          go test --tags=py36 -v .
